[package]
name = "compio-signal"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
libc = "0.2.175"
nix = { version = "0.30.1", features = ["process", "signal"] }
compio = { version = "0.17.0", features = ["io-uring", "signal"] }